<a href="https://colab.research.google.com/github/Shakestick/HelloWorld/blob/main/LabCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bob Smith


['e', 'a', 'b']


1296


In [16]:
# do this with other class / methods/ functions

print(type(int (bool("1"))))
print()
print(type(str (str("1"))))

<class 'int'>

<class 'str'>


In [10]:
x = ["e","a","b"]
y = x[1:]
y[0] = "g"
print(x)
print()

name = "Bob"
surname = " Smith"
print(name + surname)
print()

x = ["e","a","b"]
y = x[1:]
y[0] = "g"
print(x)
print()

x = 6
y = 4
print( x ** y)
print()

x = [1, -1]
y = x + [True, False]
print(y)
print()

import numpy as np
m = np.array([2,6,4])
n = np.array([2,1,1])
print(m*n)
print()



['e', 'a', 'b']


In [3]:
import numpy as np
np_heights = np.array([[1.60,1.75],[1.56,1.70],[1.49,1.68]])
print(np.mean(np_heights[:,0]))

1.55


In [ ]:
p = ['f', 'x', 'l']
q = p + ['z']
print(q)

In [6]:
import numpy as np
x = np.array([10,23,14,27])
y = np.array([3,5,7,26])
z = np.array([x,y])
print(z.shape)

(2, 4)


In [ ]:
#return 3
import numpy as np

x = [["a","b"],["c","d"]]
print(x[0][1])

np_x = np.array(x)
print(np_x[:,1])

x = [1,2,3,4,5]
print(x[1:4, 4])


z = np.array([[1,1,1],
              [3,4,4]])
print(z[1,0])
print()

#return [[3]]
z = np.array([[1,1,1],
              [3,4,4]])
print(z[1:,:1])
print()

# select code to return output 29
import numpy as np
x = [16, 2, 12, 9, 15, 17, 10]
print(x[-2] + x[-5])
print()
np_2d = np.array([[2,3],[4,5],[6,7]])
print(np_2d[2,1])
print()

print(np.array([True, 1,2]) + np.array([3,4, False]))

b
['b' 'd']


TypeError: list indices must be integers or slices, not tuple

In [ ]:
import numpy as np
print()

print()
print()
# find std of x
x = np.array([3.6,3.99,3.91])
print(np.array(np.std(x)))
print()
m = np.array([6,2,4])
n = 2
print(m + n)
print()
x = 6
y = 4
print(x ** y)
print()
x = [7,8,9]
y = [-3.3,-2,3.2] + x[0:2]
print(len(y))
print()
x = [1,2,3]
y = x
y[0] = -1
print(x)
print()
q = [37, 36, 0, 40, 32, 11]
print(len(q))
print()
p = 2
print(type(p))
print()
z = [-1.2,4,3.6,-5,1,-2,2.5]
print(max(z))
print()
#find mean of first column of costs
costs = np.column_stack(([3,2,1,3],
                         [7,6,6,5]))
mean_costs = np.mean(costs[:,0])
print(mean_costs)
print()
np_heights = np.array([[1.75,1.65,1.8,1.5],[1.56,1.70,1.4,1.29],[1.49,1.68,1.3,1.8]])
np.sort(np_heights[0])
print(np.median(np_heights[:,0]))

print()
x = [6,5,8,2,4,0]
print(x[5] + x[2])
print()
store = np.array([7,8,4,6])
cost = np.array([76,87,68,88])
np_cols = np.column_stack((store, cost))
print(np_cols)

print()
x = [0,1,-2]
x[1:] = [3,4,5]
print(x)
print()
print(sorted([-1,3,-2], reverse = True))


In [ ]:
import numpy as np
z = np.array([[9,9,3],
              [8,9,4,]]) #brackets easy to miss here.
print(z[1,0])

# ValueError: setting an array element with a sequence. The requested array has
# an inhomogeneous shape after 1 dimensions. The detected shape was (4,) +
# inhomogeneous part.

8


In [ ]:
import numpy as np

np_2d = np.array([[1.5, 6.4, 7.8, 2.2],
                  [4.3, 8.7, 1.9, 3.4],
                 [5.3, 7.3, 9.4, 2.5]])
print(np_2d[2:,2:])
print()

np_arr1 = np.array([1,2,3,4])
np_arr2 = np.array([5,6,7,8])
print()
print(np.column_stack((np_arr1, np_arr2)))

# Required Output: ['introduction', 'Python', 'DataCamp', 'R']
practise = ["introduction", "Python", "DataCamp", "R", "SQL", "Data Science"]

x = -6
y = -2
print(practise[x:y])

x = practise.index("DataCamp")
print(x)

[[9.4 2.5]]


[[1 5]
 [2 6]
 [3 7]
 [4 8]]
['introduction', 'Python', 'DataCamp', 'R']
2


In [ ]:
p = "True"
print(type(p))

x = "regulation"
print(x.replace("a", "/"))

<class 'str'>
regul/tion


In [ ]:
print(False * bool(3.2))

0


In [ ]:
x = ["1", "2", "3", "4", "5"]
numbers = list(x)
x[0] = "0"
print(numbers[0])
#

In [ ]:
import numpy as np
np_2d = np.array([[2,3],[4,5]])
print(np_2d[-2,1])

np.array([4,2,6]) * np.array([5,6,10])

3


array([20, 12, 60])

In [ ]:
# return 29 as output

import numpy as np
x = [16, 2, 12, 9, 15, 17, 10]
print(x[-2] + x[-5])

29


In [ ]:
import numpy as np
x = np.array([6,4,5,7])
y = np.array([5,1,8,7])
print(np.corrcoef(x,y))

In [ ]:
# use .columns, .loc, .iloc, itterows
#


SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-40-82ac4d95cd1e>, line 4)

In [ ]:
# standard deviation
import numpy as np
np_2d = np.array ([[5,6,1,2,3,4],[4,5,3,2,1,8],[9,10,3,7,6,5]])
print(np.median(np_2d[1,:]))



3.5


In [ ]:
# CODE COMPREHENSION
# return 0
# return 1
x = ["1", "2", "3", "4", "5"]
numbers = list(x)
x[0] = "0"
print(numbers[0])


In [ ]:
import numpy as np
x = np.array([10, 15, 22, 13, 17, 20, 8])

x_small = x[x < 17]
print(x_small)

[10 15 13  8]


In [ ]:
#required output is 2,3,4
i = 1
while True:
  if i % 3 == 0:
    break
  print(i)
  i += 1
  #outputs 1,2

i = 1
while i <=3:
  i += 1
  if i % 3 == 0:
    continue
  print(i)
  #outputs 2,4

i = 1
while i <=3:
  i = i + 1
  print(i) # outputs 2,3,4


1
2
2
4
2
3
4


In [ ]:

# errors likely due to space issues
import numpy as np

np_2d = np.array([[5, 6, 1, 2, 3, 4],
                [4, 5,3,2,1,8],
                [9, 10,3,7,6,5]])
print(np.median(np_2d[1,:]))

print("6"*(2**2))


3.5
6666


In [ ]:
x = np.array([9,5])
y = np.array([16,12])
print(np.logical_or(x < 5, y > 15))

[ True False]


In [ ]:
# use corrcoef to complete code
import numpy as np
np_heights = np.array([[1.60,1.75],[1.56,1.70],[1.49,1.68]])
print(np.corrcoef(np_heights[:,0],np_heights[:,1]))


[[1.         0.92155064]
 [0.92155064 1.        ]]


In [ ]:
import numpy as np
store = np.array(["X", "Z", "Z", "Z"])
cost = np.array([2,6,5,2])
select_cost = cost[store == "X"]
print(select_cost)

[2]


In [ ]:
import numpy as np

np_2d = np.array([[2,3],[4,5],[6,7]])
print(np_2d[2,1])
print(np_2d[0,1])
print(type(type(bool("1"))))

7
3
<class 'type'>


In [ ]:
# RETURN [False False False False False]
x = np.array([1,6,3,1,7])
bool_x = x == 5
print(bool_x)

[False False False False False]


In [ ]:
# prompt: what are the three arguments for np.random.normal() and how can I discover them?

import numpy as np

# The three arguments for np.random.normal() are:

# 1. loc: The mean (“centre”) of the distribution.
# 2. scale: The standard deviation (spread or “width”) of the distribution. Must be non-negative.
# 3. size:  Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if loc and scale are both scalars. Otherwise, np.broadcast(loc, scale).size samples are drawn.

# SUMMARY: distribution, mean, standard deviation.

# You can discover the arguments and their meaning using Python's built-in help function:

help(np.random.normal)

# Or by looking at the NumPy documentation online:
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html

In [ ]:
# Return [3.14159265 7.06858347 8.04247719]
import numpy as np
import math
radius = np.array([1,1.5,1.6])
area = math.pi * (radius ** 2)
boolean = area < 20
print(area[boolean])

[3.14159265 7.06858347 8.04247719]


In [ ]:
x = ['aPPle', 'baNANa']

def caps(li):
  #Returns a list with all elements capitalised
  def inner(w):
    #Returns a capitalised word
    w = w.upper()
    return w
  li = [inner(i) for i in li]
  return li

print(caps(x))

In [ ]:
# WHY DOESN'T THIS CODE
x = ['aPPle', 'baNANa']

def caps(li):
  #Returns a list with all elements capitalised
  def inner(w):
    #Returns a capitalised word
    return w.capitalise()
  return ([inner(li[0]), inner(li[1])])
  print(caps(x))


In [ ]:
def print_name(name):
               # Prints Helo & Person's name)
  statement = "Hello" + name + "!"
  print(statement)
print_name(' mate')

In [ ]:
# prompt: GENERATE USE CASE FOR IS NUMERIC METHOD

def is_numeric(input_string):
    """
    Checks if a given string represents a valid number (integer or floating-point).

    Args:
        input_string: The string to check.

    Returns:
        True if the string is numeric, False otherwise.
    """
    try:
        float(input_string)  # Try converting to float; handles both integers and floats
        return True
    except ValueError:
        return False

# Example usage
test_cases = ["123", "3.14", "-5", "0", "abc", "12.3a", ""]
for test_case in test_cases:
    print(f"'{test_case}' is numeric: {is_numeric(test_case)}")

In [ ]:
# is numeric

string = "12345678910"
print(string.isnumeric())


True


In [ ]:
# IS WHITE SPACE CHARACTER
# \n = new line  \t = new tab \V = VERTICAL TAB \r = carriage return
# \f = formatted string literals

string = " \n\t\r"
print(string.isspace())
#

True


In [ ]:
# COUNT THE WORDS IN A STRING

import string

example = "9 Words separated by space_but dashes '-' are not words"

# Remove punctuation from strong

after = example.translate(str.maketrans('', '', string.punctuation))
words = after.split()


# Count the words in the string

total_words = len(words)
print(total_words)

words = example.split()
print(words)



9
['9', 'Words', 'separated', 'by', 'space_but', 'dashes', "'-'", 'are', 'not', 'words']


In [ ]:
# prompt: generate count the number of words in a string with explanation

def count_words(text):
    """
    Counts the number of words in a given string.

    Args:
        text: The input string.

    Returns:
        The number of words in the string.
    """

    # Remove leading/trailing whitespace
    text = text.strip()

    # Handle empty strings
    if not text:
        return 0

    # Split the string into words using whitespace as the delimiter
    words = text.split()

    return len(words)


# Example usage (demonstrating the function with the provided code):
code_example = """
x = ['aPPle', 'baNANa']

def caps(li):
  #Returns a list with all elements capitalised
  def inner(w):
    #Returns a capitalised word
    w = w.upper()
    return w
  li = [inner(i) for i in li]
  return li

print(caps(x))
# WHY DOESN'T THIS CODE
x = ['aPPle', 'baNANa']

def caps(li):
  #Returns a list with all elements capitalised
  def inner(w):
    #Returns a capitalised word
    return w.capitalise()
  return ([inner(li[0]), inner(li[1])])
  print(caps(x))

def print_name(name):
               # Prints Helo & Person's name)
  statement = "Hello" + name + "!"
  print(statement)
print_name(' mate')

def is_numeric(input_string):
    # ... (function code)

string = "12345678910"
print(string.isnumeric())

string = " \n\t\r"
print(string.isspace())
"""

word_count = count_words(code_example)
print(f"The code example contains {word_count} words.")

In [ ]:
def convert_yards(y, feet = True):
  if feet is True:
    new_y = y * 3
  else:
    new_y = y * 36
  return new_y
print(convert_yards(10))

In [ ]:
def square(s):
  # returns area & perimeter of a square
  try:
    a = s * s
    p = 4 * s
    return a, p
  except  TypeError:
    print('s can not be a string')
square(5)


In [ ]:
temp = 15
def convert_temp (x):
  #Converts the temperature from CElsius to Fahrenheit
  global temp
  temp = (x * 1.8) + 32
convert_temp(temp)
print(temp)

In [ ]:
class Solution:
  def isPalindrome(Self, x: int) -> bool:
    if x < 0 or (x%10 == 0 and x!= 0):
      return False
      rev = 0
    while x > rev:
      rev = rev * 10 + x % 10
      x = x // 10
    return x == rev or x == rev // 10

In [ ]:
# ALPHA NUMERIC String isalnum() method. | Note a space " " , or . are not alpha numeric.
#
string = "abc123"
print(string.isalnum())

string = "abc 123"
print(string.isalnum())


In [ ]:
# prompt: How do you define a basic function?

def basic_function(parameter1, parameter2):
  """
  This is a basic function definition.

  Args:
    parameter1: The first parameter.
    parameter2: The second parameter.

  Returns:
    The result of the function.
  """
  # Function body - your code goes here
  result = parameter1 + parameter2  # Example operation
  return result

In [ ]:
# LEETCODE 125 VALID PALINDROME

# A phrase is a palindrome if, after converting all uppercase letters into lower
# case letters and removing all non-alphanumeric characters, it reads the same
# forward and backward. Alphanumeric characters include letters and numbers.

# Given a string s, return true if it is a palindrome or false otherwise.

# Eg1:
# Input:   s = "A man, a plan a canal: Panama"
# Output:  true
# Explanaton: "amanaplanacanalpanama" is a palindrome.

# Example 2:

#Input: s = "race a car"
#Output: false
#Explanation: "raceacar" is not a palindrome.
#Example 3:

#Input: s = " "
#Output: true
#Explanation: s is an empty string "" after removing non-alphanumeric characters
#Since an empty string reads the same forward and backward, it is a palindrome.


#Constraints:

# 1 <= s.length <= 2 * 105
# s consists only of printable ASCII characters.

class Solution:
  def isPalindrome(self, s: str) -> bool:
    n = len(s)
    L = 0
    R = n - 1
    while L < R:
      if not s[L].isalnum():
        L += 1
        continue
      if not s[R].isalnum():
        R -= 1
        continue
      if s[L].lower() != s[R].lower():
        return False
      L += 1
      R -= 1
    return True

In [ ]:
# prompt: Write a palindrome veriication that asks for input

def is_palindrome(text):
    processed_text = ''.join(filter(str.isalnum, text)).lower()
    return processed_text == processed_text[::-1]

input_string = input("Enter a string: ")
if is_palindrome(input_string):
    print("The string is a palindrome.")
else:
    print("The string is not a palindrome.")

print(is_palindrome())

In [ ]:
# prompt: five examples of machine learning tasks

# 1. Image Classification: Training a model to identify objects within images (e.g., cats vs. dogs, identifying different types of plants).

# 2. Sentiment Analysis:  Analyzing text data to determine the emotional tone (positive, negative, or neutral) expressed in it.  This is commonly used for analyzing customer reviews or social media posts.

# 3. Fraud Detection: Building a model to identify fraudulent transactions by analyzing patterns in financial data.

# 4. Customer Segmentation: Grouping customers based on their purchasing behavior, demographics, or other characteristics. This helps businesses tailor marketing campaigns or product recommendations to specific groups.

# 5. Time Series Forecasting: Predicting future values of a variable over time, such as stock prices, weather patterns, or sales figures.

In [2]:
# Create a new, empty list. Go through each item in the input list. Square it,
# Append it t new list  & return new list.

def square_list(input_list):
  new_list = [0]
  for item in input_list:
    new_item = item ** 2
    new_list.append(new_item)
  return new_list

In [ ]:
# prompt: five common pure functions that programmers use

import math
import string

# 1. `math.sqrt()`
#    - Purpose: Calculates the square root of a number.
#    - Purity: Always returns the same output for the same input. No side effects.
#    - Example:
#      ```python
#      result = math.sqrt(16)  # result will always be 4.0
#      ```

# 2. `string.upper()`
#    - Purpose: Converts a string to uppercase.
#    - Purity: Always returns the same uppercase version of the string. No side effects.
#    - Example:
#      ```python
#      text = "hello"
#      uppercase_text = text.upper()  # uppercase_text will always be "HELLO"
#      ```

# 3. `len()`
#    - Purpose: Returns the length of a sequence (string, list, tuple, etc.)
#    - Purity: Given the same input, it always returns the same length. Has no side effects.
#    - Example:
#       ```python
#       my_list = [1, 2, 3]
#       list_length = len(my_list) # list_length will always be 3.
#       ```

# 4. `max()`
#    - Purpose: Returns the largest item in an iterable or the largest of two or more arguments.
#    - Purity:  Always returns the same maximum value for a given input. Has no side effects.
#    - Example:
#       ```python
#       numbers = [1, 5, 2, 8, 3]
#       largest_number = max(numbers) # largest_number will always be 8.
#       ```


#      ```

In [6]:
# prompt: write the type() function from scratch

def type_(obj):
    if isinstance(obj, int):
        return "int"
    elif isinstance(obj, float):
        return "float"
    elif isinstance(obj, str):
        return "str"
    elif isinstance(obj, bool):
        return "bool"
    elif isinstance(obj, list):
        return "list"
    elif isinstance(obj, tuple):
        return "tuple"
    elif isinstance(obj, dict):
        return "dict"
    elif isinstance(obj, set):
        return "set"
    elif isinstance(obj, type(None)):
        return "NoneType"
    # Add more type checks as needed
    else:
        return "unknown"

<class 'type'>


In [ ]:
# prompt: write the isinstance() function from scratch

def type_(obj):
    if type(obj) == int:
        return "int"
    elif type(obj) == float:
        return "float"
    elif type(obj) == str:
        return "str"
    elif type(obj) == bool:
        return "bool"
    elif type(obj) == list:
        return "list"
    elif type(obj) == tuple:
        return "tuple"
    elif type(obj) == dict:
        return "dict"
    elif type(obj) == set:
        return "set"
    elif obj is None:
        return "NoneType"
    else:
        return "unknown"